### ISSUE TITLE
InputPhone: value not rendered in the hidden input field

### ISSUE THREAD

**Issue by jepsar** [jepsar/core#1]
I started with a copy of InputNumber, so the issue below will apply here as well.

https://github.com/primefaces/primefaces/issues/4543

**Comment by melloware** [comment]
Nice.  InputNumber chose to do it with a public field and a hidden field because of that component.  You might not need to make InputPhone that complicated.  I think they did that because the InputNumber had some quirks.  I could be wrong though.

**Comment by jepsar** [comment]
Alright. I'll have a look at it and maybe remove that bit if not needed. I just put it here as an issue so I wouldn't forget about it.

**Comment by melloware** [comment]
OK another suggeston rename the java package "intltelinput" to "inputphone".  That will be consistent with PF package naming.
